### ISSUE TITLE
Adding enviroment parameter support

### ISSUE THREAD

**Issue by jprltsnz** [HPENetworking/topology#67]
The new parser that would be introduced with #55 among other things support parsing environment attributes on the form of:

```
[attr1=value1]  #environment attribute
# Rest of szn string
[type= host] h1 
... 
```
In order to do something useful with this environment attributes we need to pass them along to the platform engines somehow. The two alternatives I can come up with in order to do this are:

1. Modify pynml in order to support holding this attributes somewhere 
2. Passing the environment to the platform's engine init.

Option 1 has the benefit would be the easiest and would not break topology's API, however the environment is not part of nml and it would be questionable whether this should go there. Option 2 seems more correct but it would break topology's API to the platform engine since we would be passing a new parameter along that they are not prepared to receive. This means that option 2 requires to update all platform engines' init functions to accept an environment parameter, even if they do nothing with them.

Thoughts and suggestions on how we would proceed with this?

**Comment by ocelotl** [comment]
I would prefer option 1, the mere introduction of the environment parameter is a discrepancy with NML unless it can be associated with the topology element in the standard. Comments, @carlos-jenkins, @dajose, @saenzpa?

**Comment by ocelotl** [comment]
Bump.

**Comment by sergiosmcr** [comment]
Pynml holds NML information. Are environment variables part of NML specs?
If not, perhaps passing the env vars to the platform's constructor is better.
Actually either way works for me.

Can we continue? I really want environment variables to be implemented :smile:

**Comment by saenzpa** [comment]
The NML spec is purposefully open ended so while no reference to environment is in the current schema, we should be able to extend it to include this information. As @ocelotl mentioned we can include it as part of the Topology class, or create a new one similar to the Location class. Either way the consensus so far appears to be around the first option so @jcrono feel free to follow this approach.

**Comment by dajose** [comment]
@saenzpa what do you mean by "open ended"?
