### ISSUE TITLE
Need to add support for initial switch login context.

### ISSUE THREAD

**Issue by pinedaca** [HPENetworking/topology#7]
There are some test cases on which you will need to perform a logout from vtysh and then log again. Once you perform a logout a authentication prompt will be displayed. If you access using admin/admin credentials you will have access to vtysh, if you use root/root you will access bash. Another common is when we perform a reboot on the switch. After the switch boots it will prompt the login.

Login context after performing a reboot:
OpenSwitch 0.3.0 ops-as5712 ttyS1 
ops-as5712 login:

**Comment by ocelotl** [comment]
This is a vtysh-specific issue, please open in the relevant place. The features added in 06f9d98 can be used to provide a solution in the vtysh-related code.
